In [28]:
# Cell 1: Import required libraries

from pathlib import Path
import pandas as pd
import numpy as np

print("Libraries imported successfully. ✅")

Libraries imported successfully. ✅

In [29]:
# Cell 2: Define project paths

PROJECT_ROOT = Path.cwd().parent

RAW_DATA_PATH = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "PhiUSIIL_Phishing_URL_Dataset.csv"
)

PROCESSED_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
)

PROCESSED_DATA_PATH = (
    PROCESSED_DIR
    / "cleaned_dataset.csv"
)

print("Project root:")
print(PROJECT_ROOT)

print("\nRaw dataset:")
print(RAW_DATA_PATH)

print("\nProcessed dataset:")
print(PROCESSED_DATA_PATH)

Project root:
c:\Users\Manid\project1

Raw dataset:
c:\Users\Manid\project1\data\raw\PhiUSIIL_Phishing_URL_Dataset.csv

Processed dataset:
c:\Users\Manid\project1\data\processed\cleaned_dataset.csv

In [30]:
# Cell 3: Verify input dataset

if not RAW_DATA_PATH.exists():

    raise FileNotFoundError(
        f"Dataset not found:\n{RAW_DATA_PATH}\n\n"
        "Make sure the CSV is inside data/raw/"
    )

print("PhiUSIIL dataset found. ✅")

PhiUSIIL dataset found. ✅

In [31]:
# Cell 4: Load the raw dataset

df = pd.read_csv(
    RAW_DATA_PATH,
    low_memory=False
)

print("Dataset loaded successfully. ✅")
print(f"Rows    : {len(df):,}")
print(f"Columns : {len(df.columns):,}")

Dataset loaded successfully. ✅
Rows    : 235,795
Columns : 56

In [32]:
# Cell 5: Create a working copy

clean_df = df.copy()

print("Working copy created. ✅")

Working copy created. ✅

In [33]:
clean_df

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.000000,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.000000,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.000000,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.000000,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.000000,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235790,660997.txt,https://www.skincareliving.com,29,www.skincareliving.com,22,0,com,100.000000,1.000000,0.522907,...,1,0,1,51,7,21,187,2,191,1
235791,77185.txt,https://www.winchester.gov.uk,28,www.winchester.gov.uk,21,0,uk,100.000000,0.785714,0.028555,...,1,0,0,50,1,7,88,0,31,1
235792,622132.txt,https://www.nononsensedesign.be,30,www.nononsensedesign.be,23,0,be,100.000000,1.000000,0.003319,...,0,0,1,27,10,30,58,2,67,1
235793,7503962.txt,https://patient-cell-40f5.updatedlogmylogin.wo...,55,patient-cell-40f5.updatedlogmylogin.workers.dev,47,0,dev,28.157537,0.465116,0.000961,...,0,0,0,0,0,3,0,0,0,0
235794,384822.txt,https://www.alternativefinland.com,33,www.alternativefinland.com,26,0,com,100.000000,1.000000,0.522907,...,0,0,1,21,6,18,256,0,261,1

In [34]:
df

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.000000,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.000000,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.000000,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.000000,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.000000,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235790,660997.txt,https://www.skincareliving.com,29,www.skincareliving.com,22,0,com,100.000000,1.000000,0.522907,...,1,0,1,51,7,21,187,2,191,1
235791,77185.txt,https://www.winchester.gov.uk,28,www.winchester.gov.uk,21,0,uk,100.000000,0.785714,0.028555,...,1,0,0,50,1,7,88,0,31,1
235792,622132.txt,https://www.nononsensedesign.be,30,www.nononsensedesign.be,23,0,be,100.000000,1.000000,0.003319,...,0,0,1,27,10,30,58,2,67,1
235793,7503962.txt,https://patient-cell-40f5.updatedlogmylogin.wo...,55,patient-cell-40f5.updatedlogmylogin.workers.dev,47,0,dev,28.157537,0.465116,0.000961,...,0,0,0,0,0,3,0,0,0,0
235794,384822.txt,https://www.alternativefinland.com,33,www.alternativefinland.com,26,0,com,100.000000,1.000000,0.522907,...,0,0,1,21,6,18,256,0,261,1

In [35]:
# Cell 6: Validate required columns

REQUIRED_COLUMNS = {
    "URL",
    "label"
}

missing_columns = (
    REQUIRED_COLUMNS
    - set(clean_df.columns)
)

if missing_columns:

    raise ValueError(
        "Required columns are missing: "
        f"{sorted(missing_columns)}"
    )

print("Required columns found. ✅")
print("URL")
print("label")

Required columns found. ✅
URL
label

In [36]:
# Cell 7: Record original dataset size

original_rows = len(clean_df)
original_columns = len(clean_df.columns)

print(f"Original rows    : {original_rows:,}")
print(f"Original columns : {original_columns:,}")

Original rows    : 235,795
Original columns : 56

In [37]:
# Cell 8: Analyze missing values

missing_values = (
    clean_df
    .isnull()
    .sum()
    .sort_values(
        ascending=False
    )
)

missing_values = missing_values[
    missing_values > 0
]

if missing_values.empty:

    print("No missing values found. ✅")

else:

    print("Missing values:")
    print(missing_values)

No missing values found. ✅

In [38]:
# Cell 9: Remove rows missing critical fields

before = len(clean_df)

clean_df = clean_df.dropna(
    subset=["URL", "label"]
).copy()

removed = before - len(clean_df)

print(f"Rows removed: {removed:,}")
print(f"Rows remaining: {len(clean_df):,}")

Rows removed: 0
Rows remaining: 235,795

In [39]:
# Cell 10: Clean URL values

clean_df["URL"] = (
    clean_df["URL"]
    .astype(str)
    .str.strip()
)

print("URL whitespace cleaned. ✅")

URL whitespace cleaned. ✅

In [40]:
# Cell 11: Remove empty URL records

before = len(clean_df)

clean_df = clean_df[
    clean_df["URL"].str.len() > 0
].copy()

removed = before - len(clean_df)

print(f"Empty URLs removed: {removed:,}")
print(f"Rows remaining: {len(clean_df):,}")

Empty URLs removed: 0
Rows remaining: 235,795

In [41]:
# Cell 12: Convert labels to numeric

clean_df["label"] = pd.to_numeric(
    clean_df["label"],
    errors="coerce"
)

print(
    clean_df["label"]
    .value_counts(dropna=False)
)

label
1    134850
0    100945
Name: count, dtype: int64

In [42]:
# Cell 13: Remove invalid labels

before = len(clean_df)

clean_df = clean_df[
    clean_df["label"].isin([0, 1])
].copy()

removed = before - len(clean_df)

print(f"Invalid label rows removed: {removed:,}")

Invalid label rows removed: 0

In [43]:
# Cell 14: Set final label data type

clean_df["label"] = (
    clean_df["label"]
    .astype("int8")
)

print(
    "Label data type:",
    clean_df["label"].dtype
)

Label data type: int8

In [44]:
# Cell 15: Remove duplicate records

before = len(clean_df)

clean_df = (
    clean_df
    .drop_duplicates()
    .reset_index(drop=True)
)

removed = before - len(clean_df)

print(f"Duplicate rows removed: {removed:,}")
print(f"Rows remaining: {len(clean_df):,}")

Duplicate rows removed: 0
Rows remaining: 235,795

In [45]:
# Cell 16: Check duplicate URLs

duplicate_urls = (
    clean_df["URL"]
    .duplicated()
    .sum()
)

print(
    f"Duplicate URL entries: "
    f"{duplicate_urls:,}"
)

Duplicate URL entries: 425

In [46]:
# Cell 17: Final label distribution

label_counts = (
    clean_df["label"]
    .value_counts()
    .sort_index()
)

print("Final label distribution")
print("=" * 40)

for label, count in label_counts.items():

    name = (
        "Phishing"
        if label == 0
        else "Legitimate"
    )

    print(
        f"{label} ({name}): "
        f"{count:,}"
    )

Final label distribution
========================================
0 (Phishing): 100,945
1 (Legitimate): 134,850

In [47]:
# Cell 18: Final missing-value check

remaining_missing = (
    clean_df
    .isnull()
    .sum()
)

remaining_missing = remaining_missing[
    remaining_missing > 0
]

if remaining_missing.empty:

    print(
        "No missing values remain. ✅"
    )

else:

    print(
        "Remaining missing values:"
    )

    print(remaining_missing)

No missing values remain. ✅

In [48]:
# Cell 19: Check final data types

print(
    clean_df.dtypes.to_string()
)

FILENAME                          str
URL                               str
URLLength                       int64
Domain                            str
DomainLength                    int64
IsDomainIP                      int64
TLD                               str
URLSimilarityIndex            float64
CharContinuationRate          float64
TLDLegitimateProb             float64
URLCharProb                   float64
TLDLength                       int64
NoOfSubDomain                   int64
HasObfuscation                  int64
NoOfObfuscatedChar              int64
ObfuscationRatio              float64
NoOfLettersInURL                int64
LetterRatioInURL              float64
NoOfDegitsInURL                 int64
DegitRatioInURL               float64
NoOfEqualsInURL                 int64
NoOfQMarkInURL                  int64
NoOfAmpersandInURL              int64
NoOfOtherSpecialCharsInURL      int64
SpacialCharRatioInURL         float64
IsHTTPS                         int64
LineOfCode                      int64
LargestLineLength               int64
HasTitle                        int64
Title                             str
DomainTitleMatchScore         float64
URLTitleMatchScore            float64
HasFavicon                      int64
Robots                          int64
IsResponsive                    int64
NoOfURLRedirect                 int64
NoOfSelfRedirect                int64
HasDescription                  int64
NoOfPopup                       int64
NoOfiFrame                      int64
HasExternalFormSubmit           int64
HasSocialNet                    int64
HasSubmitButton                 int64
HasHiddenFields                 int64
HasPasswordField                int64
Bank                            int64
Pay                             int64
Crypto                          int64
HasCopyrightInfo                int64
NoOfImage                       int64
NoOfCSS                         int64
NoOfJS                          int64
NoOfSelfRef                     int64
NoOfEmptyRef                    int64
NoOfExternalRef                 int64
label                            int8

In [49]:
# Cell 20: Final dataset validation

assert "URL" in clean_df.columns
assert "label" in clean_df.columns

assert clean_df["URL"].notna().all()
assert clean_df["URL"].str.len().gt(0).all()

assert clean_df["label"].isin([0, 1]).all()

assert not clean_df.empty

print("All validation checks passed. ✅")

All validation checks passed. ✅

In [50]:
# Cell 21: Cleaning summary

final_rows = len(clean_df)

rows_removed = (
    original_rows - final_rows
)

print("=" * 70)
print("PHISHGUARD AI - DATA CLEANING SUMMARY")
print("=" * 70)

print(
    f"Original rows : {original_rows:,}"
)

print(
    f"Final rows    : {final_rows:,}"
)

print(
    f"Rows removed  : {rows_removed:,}"
)

print(
    f"Columns       : {len(clean_df.columns):,}"
)

print(
    f"Missing values: "
    f"{clean_df.isnull().sum().sum():,}"
)

print(
    f"Duplicates    : "
    f"{clean_df.duplicated().sum():,}"
)

print("\nCleaning completed successfully. ✅")

======================================================================
PHISHGUARD AI - DATA CLEANING SUMMARY
======================================================================
Original rows : 235,795
Final rows    : 235,795
Rows removed  : 0
Columns       : 56
Missing values: 0
Duplicates    : 0

Cleaning completed successfully. ✅

In [51]:
# Cell 22: Create processed-data directory

PROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print(
    "Processed directory ready. ✅"
)

Processed directory ready. ✅

In [52]:
# Cell 23: Save cleaned dataset

clean_df.to_csv(
    PROCESSED_DATA_PATH,
    index=False
)

print(
    "Cleaned dataset saved successfully. ✅"
)

print(
    f"\nSaved to:\n{PROCESSED_DATA_PATH}"
)

Cleaned dataset saved successfully. ✅

Saved to:
c:\Users\Manid\project1\data\processed\cleaned_dataset.csv

In [53]:
# Cell 24: Verify processed dataset

if PROCESSED_DATA_PATH.exists():

    file_size_mb = (
        PROCESSED_DATA_PATH.stat().st_size
        / (1024 * 1024)
    )

    print("Processed dataset verified. ✅")
    print(
        f"File size: {file_size_mb:.2f} MB"
    )

else:

    raise FileNotFoundError(
        "Processed dataset was not created."
    )

Processed dataset verified. ✅
File size: 56.42 MB