In [120]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("Project root:")
print(PROJECT_ROOT)

Project root:
c:\Users\Manid\project1

In [121]:
from src.data.loader import load_raw_dataset, dataset_info

print("Loader imported successfully. ✅")

Loader imported successfully. ✅

In [122]:
dataset = load_raw_dataset()

print("Dataset loaded successfully. ✅")
print("Rows:", dataset.shape[0])
print("Columns:", dataset.shape[1])

Dataset loaded successfully. ✅
Rows: 235795
Columns: 56

In [123]:
dataset_info(dataset)

======================================================================
PHISHGUARD AI - DATASET INFORMATION
======================================================================

Dataset shape:
(235795, 56)

Column names:
FILENAME
URL
URLLength
Domain
DomainLength
IsDomainIP
TLD
URLSimilarityIndex
CharContinuationRate
TLDLegitimateProb
URLCharProb
TLDLength
NoOfSubDomain
HasObfuscation
NoOfObfuscatedChar
ObfuscationRatio
NoOfLettersInURL
LetterRatioInURL
NoOfDegitsInURL
DegitRatioInURL
NoOfEqualsInURL
NoOfQMarkInURL
NoOfAmpersandInURL
NoOfOtherSpecialCharsInURL
SpacialCharRatioInURL
IsHTTPS
LineOfCode
LargestLineLength
HasTitle
Title
DomainTitleMatchScore
URLTitleMatchScore
HasFavicon
Robots
IsResponsive
NoOfURLRedirect
NoOfSelfRedirect
HasDescription
NoOfPopup
NoOfiFrame
HasExternalFormSubmit
HasSocialNet
HasSubmitButton
HasHiddenFields
HasPasswordField
Bank
Pay
Crypto
HasCopyrightInfo
NoOfImage
NoOfCSS
NoOfJS
NoOfSelfRef
NoOfEmptyRef
NoOfExternalRef
label

Missing values:
FILENAME                      0
URL                           0
URLLength                     0
Domain                        0
DomainLength                  0
IsDomainIP                    0
TLD                           0
URLSimilarityIndex            0
CharContinuationRate          0
TLDLegitimateProb             0
URLCharProb                   0
TLDLength                     0
NoOfSubDomain                 0
HasObfuscation                0
NoOfObfuscatedChar            0
ObfuscationRatio              0
NoOfLettersInURL              0
LetterRatioInURL              0
NoOfDegitsInURL               0
DegitRatioInURL               0
NoOfEqualsInURL               0
NoOfQMarkInURL                0
NoOfAmpersandInURL            0
NoOfOtherSpecialCharsInURL    0
SpacialCharRatioInURL         0
IsHTTPS                       0
LineOfCode                    0
LargestLineLength             0
HasTitle                      0
Title                         0
DomainTitleMatchScore         0
URLTitleMatchScore            0
HasFavicon                    0
Robots                        0
IsResponsive                  0
NoOfURLRedirect               0
NoOfSelfRedirect              0
HasDescription                0
NoOfPopup                     0
NoOfiFrame                    0
HasExternalFormSubmit         0
HasSocialNet                  0
HasSubmitButton               0
HasHiddenFields               0
HasPasswordField              0
Bank                          0
Pay                           0
Crypto                        0
HasCopyrightInfo              0
NoOfImage                     0
NoOfCSS                       0
NoOfJS                        0
NoOfSelfRef                   0
NoOfEmptyRef                  0
NoOfExternalRef               0
label                         0
dtype: int64

Duplicate rows:
0

First 5 rows:
     FILENAME                                 URL  URLLength  \
0  521848.txt    https://www.southbankmosaics.com         31
1   31372.txt            https://www.uni-mainz.de         23
2  597387.txt      https://www.voicefmradio.co.uk         29
3  554095.txt         https://www.sfnmjournal.com         26
4  151578.txt  https://www.rewildingargentina.org         33

                       Domain  DomainLength  IsDomainIP  TLD  \
0    www.southbankmosaics.com            24           0  com
1            www.uni-mainz.de            16           0   de
2      www.voicefmradio.co.uk            22           0   uk
3         www.sfnmjournal.com            19           0  com
4  www.rewildingargentina.org            26           0  org

   URLSimilarityIndex  CharContinuationRate  TLDLegitimateProb  ...  Pay  \
0               100.0              1.000000           0.522907  ...    0
1               100.0              0.666667           0.032650  ...    0
2               100.0              0.866667           0.028555  ...    0
3               100.0              1.000000           0.522907  ...    1
4               100.0              1.000000           0.079963  ...    1

   Crypto  HasCopyrightInfo  NoOfImage  NoOfCSS  NoOfJS  NoOfSelfRef  \
0       0                 1         34       20      28          119
1       0                 1         50        9       8           39
2       0                 1         10        2       7           42
3       1                 1          3       27      15           22
4       0                 1        244       15      34           72

   NoOfEmptyRef  NoOfExternalRef  label
0             0              124      1
1             0              217      1
2             2                5      1
3             1               31      1
4             1               85      1

[5 rows x 56 columns]

In [124]:
# Cell 3: Dataset path

DATASET_PATH = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "PhiUSIIL_Phishing_URL_Dataset.csv"
)

print("Dataset path:")
print(DATASET_PATH)

print("\nDataset exists:", DATASET_PATH.exists())

Dataset path:
c:\Users\Manid\project1\data\raw\PhiUSIIL_Phishing_URL_Dataset.csv

Dataset exists: True

In [125]:
df = pd.read_csv(
    DATASET_PATH,
    low_memory=False
)

print("Dataset loaded successfully.")
print("Shape:", df.shape)

Dataset loaded successfully.
Shape: (235795, 56)

In [126]:
from src.data.cleaner import clean_dataset

print("Cleaner imported successfully. ✅")

Cleaner imported successfully. ✅

In [127]:
cleaned_dataset = clean_dataset(dataset)

======================================================================
PHISHGUARD AI - DATA CLEANING
======================================================================

Original shape:
(235795, 56)

Cleaned shape:
(235370, 56)

Remaining missing values:
URL      0
label    0
dtype: int64

Label distribution:
label
0    100520
1    134850
Name: count, dtype: int64

Data cleaning completed successfully. ✅

In [128]:
cleaned_dataset.head()

,FILENAME,URL,URLLength,Domain,DomainLength,IsDomainIP,TLD,URLSimilarityIndex,CharContinuationRate,TLDLegitimateProb,...,Pay,Crypto,HasCopyrightInfo,NoOfImage,NoOfCSS,NoOfJS,NoOfSelfRef,NoOfEmptyRef,NoOfExternalRef,label
0,521848.txt,https://www.southbankmosaics.com,31,www.southbankmosaics.com,24,0,com,100.0,1.000000,0.522907,...,0,0,1,34,20,28,119,0,124,1
1,31372.txt,https://www.uni-mainz.de,23,www.uni-mainz.de,16,0,de,100.0,0.666667,0.032650,...,0,0,1,50,9,8,39,0,217,1
2,597387.txt,https://www.voicefmradio.co.uk,29,www.voicefmradio.co.uk,22,0,uk,100.0,0.866667,0.028555,...,0,0,1,10,2,7,42,2,5,1
3,554095.txt,https://www.sfnmjournal.com,26,www.sfnmjournal.com,19,0,com,100.0,1.000000,0.522907,...,1,1,1,3,27,15,22,1,31,1
4,151578.txt,https://www.rewildingargentina.org,33,www.rewildingargentina.org,26,0,org,100.0,1.000000,0.079963,...,1,0,1,244,15,34,72,1,85,1

In [129]:
cleaned_dataset.shape

(235370, 56)

In [130]:
from pathlib import Path

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

PROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

CLEANED_DATA_PATH = (
    PROCESSED_DIR /
    "cleaned_phishing_dataset.csv"
)

cleaned_dataset.to_csv(
    CLEANED_DATA_PATH,
    index=False
)

print("Cleaned dataset saved successfully. ✅")
print(CLEANED_DATA_PATH)

Cleaned dataset saved successfully. ✅
c:\Users\Manid\project1\data\processed\cleaned_phishing_dataset.csv

In [131]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print("PROJECT ROOT:")
print(PROJECT_ROOT)

print("\nSRC EXISTS:")
print((PROJECT_ROOT / "src").exists())

print("\nFEATURES EXISTS:")
print((PROJECT_ROOT / "src" / "features").exists())

print("\nURL_FEATURES.PY EXISTS:")
print(
    (
        PROJECT_ROOT
        / "src"
        / "features"
        / "url_features.py"
    ).exists()
)

PROJECT ROOT:
c:\Users\Manid\project1

SRC EXISTS:
True

FEATURES EXISTS:
True

URL_FEATURES.PY EXISTS:
True

In [132]:
from src.features.url_features import (
    extract_url_features,
    extract_features_from_dataframe
)

print(
    "URL feature extractor imported successfully. ✅"
)

URL feature extractor imported successfully. ✅

In [133]:
# ============================================================
# CELL 10 - TEST URL FEATURE EXTRACTION
# ============================================================

TEST_URL = "https://www.google.com"

test_features = extract_url_features(TEST_URL)

print("=" * 70)
print("URL FEATURE EXTRACTION TEST")
print("=" * 70)

print("\nTest URL:")
print(TEST_URL)

print("\nExtracted Features:")

for feature_name, feature_value in test_features.items():
    print(
        f"{feature_name:35} : {feature_value}"
    )

print("\nNumber of features:")
print(len(test_features))

======================================================================
URL FEATURE EXTRACTION TEST
======================================================================

Test URL:
https://www.google.com

Extracted Features:
url_length                          : 22
hostname_length                     : 14
path_length                         : 0
query_length                        : 0
digit_count                         : 0
letter_count                        : 17
special_character_count             : 5
dot_count                           : 2
slash_count                         : 2
hyphen_count                        : 0
underscore_count                    : 0
question_count                      : 0
equal_count                         : 0
ampersand_count                     : 0
percent_count                       : 0
subdomain_count                     : 1
has_https                           : 1
has_http                            : 0
has_at_symbol                       : 0
has_ip_address                      : 0
has_query                           : 0
has_fragment                        : 0
has_percent_encoding                : 0
has_suspicious_double_slash         : 0
url_entropy                         : 3.663532754804254

Number of features:
25

In [134]:
# ============================================================
# CELL 13 - DISPLAY FEATURE NAMES
# ============================================================

print("Features extracted:")
print()

for number, feature_name in enumerate(
    test_features.keys(),
    start=1
):
    print(
        f"{number:2}. {feature_name}"
    )

Features extracted:

 1. url_length
 2. hostname_length
 3. path_length
 4. query_length
 5. digit_count
 6. letter_count
 7. special_character_count
 8. dot_count
 9. slash_count
10. hyphen_count
11. underscore_count
12. question_count
13. equal_count
14. ampersand_count
15. percent_count
16. subdomain_count
17. has_https
18. has_http
19. has_at_symbol
20. has_ip_address
21. has_query
22. has_fragment
23. has_percent_encoding
24. has_suspicious_double_slash
25. url_entropy

In [135]:
# ============================================================
# CHECK ALL 25 URL FEATURES
# ============================================================

print("Number of features:", len(test_features))
print()

for number, feature_name in enumerate(
    test_features.keys(),
    start=1
):
    print(f"{number:2}. {feature_name}")

Number of features: 25

 1. url_length
 2. hostname_length
 3. path_length
 4. query_length
 5. digit_count
 6. letter_count
 7. special_character_count
 8. dot_count
 9. slash_count
10. hyphen_count
11. underscore_count
12. question_count
13. equal_count
14. ampersand_count
15. percent_count
16. subdomain_count
17. has_https
18. has_http
19. has_at_symbol
20. has_ip_address
21. has_query
22. has_fragment
23. has_percent_encoding
24. has_suspicious_double_slash
25. url_entropy

In [136]:
# ============================================================
# CHECK FEATURE DATA
# ============================================================

print("Feature names:")
print(list(test_features.keys()))

print("\nFeature values:")
print(list(test_features.values()))

Feature names:
['url_length', 'hostname_length', 'path_length', 'query_length', 'digit_count', 'letter_count', 'special_character_count', 'dot_count', 'slash_count', 'hyphen_count', 'underscore_count', 'question_count', 'equal_count', 'ampersand_count', 'percent_count', 'subdomain_count', 'has_https', 'has_http', 'has_at_symbol', 'has_ip_address', 'has_query', 'has_fragment', 'has_percent_encoding', 'has_suspicious_double_slash', 'url_entropy']

Feature values:
[22, 14, 0, 0, 0, 17, 5, 2, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 3.663532754804254]

In [137]:
# ============================================================
# CELL 16 - EXTRACT FEATURES FROM COMPLETE DATASET
# ============================================================

feature_rows = extract_features_from_dataframe(
    cleaned_dataset,
    url_column="URL"
)

url_features_df = pd.DataFrame(
    feature_rows
)

print("=" * 70)
print("URL FEATURE DATASET CREATED")
print("=" * 70)

print("\nShape:")
print(url_features_df.shape)

print("\nNumber of features:")
print(len(url_features_df.columns))

print("\nFeature columns:")
for number, column in enumerate(
    url_features_df.columns,
    start=1
):
    print(f"{number:2}. {column}")

print("\nFirst 5 rows:")
display(url_features_df.head())

======================================================================
URL FEATURE DATASET CREATED
======================================================================

Shape:
(235370, 25)

Number of features:
25

Feature columns:
 1. url_length
 2. hostname_length
 3. path_length
 4. query_length
 5. digit_count
 6. letter_count
 7. special_character_count
 8. dot_count
 9. slash_count
10. hyphen_count
11. underscore_count
12. question_count
13. equal_count
14. ampersand_count
15. percent_count
16. subdomain_count
17. has_https
18. has_http
19. has_at_symbol
20. has_ip_address
21. has_query
22. has_fragment
23. has_percent_encoding
24. has_suspicious_double_slash
25. url_entropy

First 5 rows:

,url_length,hostname_length,path_length,query_length,digit_count,letter_count,special_character_count,dot_count,slash_count,hyphen_count,...,subdomain_count,has_https,has_http,has_at_symbol,has_ip_address,has_query,has_fragment,has_percent_encoding,has_suspicious_double_slash,url_entropy
0,32,24,0,0,0,27,5,2,2,0,...,1,1,0,0,0,0,0,0,0,3.929229
1,24,16,0,0,0,18,6,2,2,1,...,1,1,0,0,0,0,0,0,0,3.970176
2,30,22,0,0,0,24,6,3,2,0,...,2,1,0,0,0,0,0,0,0,4.164735
3,27,19,0,0,0,22,5,2,2,0,...,1,1,0,0,0,0,0,0,0,4.060262
4,34,26,0,0,0,29,5,2,2,0,...,1,1,0,0,0,0,0,0,0,3.917626

In [138]:
# ============================================================
# CELL 17 - ADD LABEL
# ============================================================

url_features_df["label"] = (
    cleaned_dataset["label"].values
)

print("=" * 70)
print("LABEL ADDED")
print("=" * 70)

print("\nFinal shape:")
print(url_features_df.shape)

print("\nColumns:")
print(list(url_features_df.columns))

print("\nLabel distribution:")
print(
    url_features_df["label"]
    .value_counts()
    .sort_index()
)

======================================================================
LABEL ADDED
======================================================================

Final shape:
(235370, 26)

Columns:
['url_length', 'hostname_length', 'path_length', 'query_length', 'digit_count', 'letter_count', 'special_character_count', 'dot_count', 'slash_count', 'hyphen_count', 'underscore_count', 'question_count', 'equal_count', 'ampersand_count', 'percent_count', 'subdomain_count', 'has_https', 'has_http', 'has_at_symbol', 'has_ip_address', 'has_query', 'has_fragment', 'has_percent_encoding', 'has_suspicious_double_slash', 'url_entropy', 'label']

Label distribution:
label
0    100520
1    134850
Name: count, dtype: int64

In [139]:
# ============================================================
# CELL 18 - SAVE FEATURE DATASET
# ============================================================

PROCESSED_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
)

PROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

FEATURES_PATH = (
    PROCESSED_DIR
    / "phishing_features.csv"
)

url_features_df.to_csv(
    FEATURES_PATH,
    index=False
)

print("=" * 70)
print("FEATURE DATASET SAVED SUCCESSFULLY ✅")
print("=" * 70)

print("\nPath:")
print(FEATURES_PATH)

print("\nFile exists:")
print(FEATURES_PATH.exists())

print("\nFile size:")
print(
    FEATURES_PATH.stat().st_size,
    "bytes"
)

======================================================================
FEATURE DATASET SAVED SUCCESSFULLY ✅
======================================================================

Path:
c:\Users\Manid\project1\data\processed\phishing_features.csv

File exists:
True

File size:
17093616 bytes

In [140]:
# Cell 19: Final summary

print("=" * 70)
print("PHISHGUARD AI - DATASET ANALYSIS COMPLETE")
print("=" * 70)

print(f"Rows              : {len(df):,}")
print(f"Columns           : {len(df.columns):,}")
print(f"Duplicate rows    : {df.duplicated().sum():,}")
print(f"Missing values    : {df.isnull().sum().sum():,}")
print(f"Unique labels     : {sorted(df['label'].unique())}")

print("\nLabel mapping:")
print("0 → Phishing")
print("1 → Legitimate")

print("\nDataset analysis completed successfully. ✅")

======================================================================
PHISHGUARD AI - DATASET ANALYSIS COMPLETE
======================================================================
Rows              : 235,795
Columns           : 56
Duplicate rows    : 0
Missing values    : 0
Unique labels     : [np.int64(0), np.int64(1)]

Label mapping:
0 → Phishing
1 → Legitimate

Dataset analysis completed successfully. ✅